### ISSUE TITLE
Post your ideas for format readers, filters, and macros!

### ISSUE THREAD

**Issue by banesullivan** [OpenGeoVis/PVGeo#1]
Please feel free to post your ideas for readers*, filters, and macros so that we can make this repo work for your visualization needs! Also if there is some sort of visualization task you need to complete, describe it and we can make an [example page on the Docs](http://pvgp.io) in the resources section.

Don't be shy, request features and keep us busy!

*Note: please post file formats for the readers such as links to descriptions or example files.*

**Comment by craigmillernz** [comment]
If you can implement a UBC octree mesh reader that would be great!  There are quite a few tools that can read the Tensor mesh, but only UBC meshtools can read octree. 

http://giftoolscookbook.readthedocs.io/en/latest/content/fileFormats/meshOctreefile.html

**Comment by banesullivan** [comment]
Hi Craig, I think I can implement a file reader for the UBC OCTree mesh and I would be happy to get to this in the next few weeks. Would you be willing to provide an example file with some screenshots for me to work with? Let's talk over email: chrsulli@mines.edu
