### ISSUE TITLE
EsriGridReader returns active_scalars is none ?

### ISSUE THREAD

**Issue by leminhson** [OpenGeoVis/PVGeo#103]
**Describe the bug**
When running the example from the page: (https://pvgeo.org/examples/grids/read-esri.html) I received this error:
_KeyError: 'Data array (None) not present in this dataset.'_

**Screenshots**
After checking the content of **dem** returned by **EsriGridReader** function, I notice that:
**1) active_scalars is none**
![active_scalar](https://user-images.githubusercontent.com/14102005/133190351-68dd417c-ebe2-499d-9517-7672d57b3b49.png)

**2) points array did not get z-values**. All z-values are zeros
![points_array](https://user-images.githubusercontent.com/14102005/133190441-54490068-7953-4abc-9638-10ccabea9ac0.png)

I am afraid that there is something incompatible between **pyvista** and **PVGeo** but could not find out the reason.

**Desktop (please complete the following information):**
 - OS: Windows 7 64bit
 - Python 3.8.8
 - pyvista 0.32.1
 - PVGeo 2.1.0

**Comment by leminhson** [comment]
This example can run smoothly with **pyvista version 0.31.3** with no error.
So the problem should be from **_pyvista version 0.32.1_**

**Comment by banesullivan** [comment]
Thanks for bringing this up. I'll see if I can find time to update this

**Comment by banesullivan** [comment]
Resolved on the main branch. Will release a patch to pypi soon
