### ISSUE TITLE
ESRI Grid how to read archive

### ISSUE THREAD

**Issue by Gloomy87** [OpenGeoVis/PVGeo#104]
How to read file not from example, but real archive, for example from here 
https://data.apps.fao.org/map/catalog/srv/eng/catalog.search#/metadata/e98b4000-0615-11dd-af4e-0017f293bd28

File to download:
https://storage.googleapis.com/fao-maps-catalog-data/uuid/e98b4000-0615-11dd-af4e-0017f293bd28/resources/luswrld.zip

**Comment by banesullivan** [comment]
Those files do not conform to the ESRI grid format I'm used to, i.e. https://en.wikipedia.org/wiki/Esri_grid

I don't think that is support by PVGeo at this time

**Comment by banesullivan** [comment]
GDAL should be able to open them though and the latest versions of ParaView have a GDAL reader baked in

https://gdal.org/drivers/raster/arcinfo_grid_format.html#arc-info-binary-grid-format
