### ISSUE TITLE
PVGeo installation for Paraview integration

### ISSUE THREAD

**Issue by UliWoe** [OpenGeoVis/PVGeo#106]
Unfortunately the procedure described in Getting Started fails, after activation of pvgeoenv the installation of PVGeo runs into an error, as imageio requires Python >=3.5. Any workaround?

**Comment by banesullivan** [comment]
at this time, I do not have a good workaround for this. I currently only have the bandwidth to support PVGeo with PyVista at this time.

With that said... have you tried updating ParaView? I have v5.9 locally which bundles Python 3.8.6 which should be compatible

**Comment by MpPina** [comment]
Hi,

Is there any solution to this issue now?? or, there is no way to use PVGeo with Paraview??

Cheers

**Comment by banesullivan** [comment]
PVGeo can still be used in ParaView, I just need to update the installation instructions. I'll see if I can get around to this soon

**Comment by MpPina** [comment]
Ok, thanks for your quick answer. Looking forward to it!!

**Comment by banesullivan** [comment]
Working on this... currently blocked by https://github.com/pyvista/pyvista/issues/3224

**Comment by banesullivan** [comment]
FYI https://github.com/Kitware/ParaView/blob/master/Web/Python/paraview/web/venv.py

**Comment by banesullivan** [comment]
I have dropped support for ParaView, please use PyVista instead: docs.pyvista.org
