### ISSUE TITLE
VoxelizePoints ERROR: In vtkPythonAlgorithm.

### ISSUE THREAD

**Issue by RichardScottOZ** [OpenGeoVis/PVGeo#109]
**Describe the bug**
Failure to run

```python
import PVGeo
voxelizer = PVGeo.filters.VoxelizePoints()

voxelizer = PVGeo.filters.VoxelizePoints()
voxelizer.set_deltas(5000, 5000, 50) # Your block sizes in dx, dy, dz
voxelizer.set_estimate_grid(True) # This is crucial for this point cloud
grid = voxelizer.apply(point_cloud)
```

**Behavior**
voxlised point cloud

**To Reproduce**
See above

**Screenshots**
```
ERROR: In vtkPythonAlgorithm.cxx, line 112
vtkPythonAlgorithm (000002DC7E8D56B0): Failure when calling method: "ProcessRequest":
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - NumPy Version: 1.23.4

**Additional context**
Please add any other context about the problem here. Feel free to attach sample data files or python scripts that might reproduce the issue. If the issue has tracebacks in the output console, please check the *Show full messages* checkbox and copy/paste that output here.

vtk 9.2.6

**Comment by RichardScottOZ** [comment]
Possibly a vtk version thing - e.g. need older?  Can try if I still have an older environment set up.

**Comment by RichardScottOZ** [comment]
although this could be one of those flip the set_estimate grid - e.g. non-uniform set of points so don't try?

**Comment by banesullivan** [comment]
It's tough to tell what went wrong here without the source data. This algorithm is highly sensitive to the input data and the input data must have an implicit structure under a handful of assumptions (assumptions that may or may not be documented in the filter class 😉)

**Comment by RichardScottOZ** [comment]
Yeah, no need to worry too much here, I got something to work with setting a flag the right way.

Basically the drillcollars across Australia - so highly biased to certain regions.
