### ISSUE TITLE
PVGeo Paraview integration on Windows

### ISSUE THREAD

**Issue by Geoscientist1** [OpenGeoVis/PVGeo#110]
Dear all,

I am trying to use Paraview for my research visualization, at the same time I am using python (Pycharm IDE) to write my code.
I have followed the guide (https://pvgeo.org/overview/getting-started.html) but encountered an issue when loading the plugins through ParaView’s Plugin Manager:

![image](https://github.com/OpenGeoVis/PVGeo/assets/155265538/e60fbc12-e696-47a2-ad5f-d67e0b380e27)
![image](https://github.com/OpenGeoVis/PVGeo/assets/155265538/f18b50d4-6348-45a3-8725-f0baf030cec3)

The second screenshot is in Norwegian, but it basically says that there is something wrong with the file.

Thank you very much in advance.

**Comment by banesullivan** [comment]
Hi @Geoscientist1, I haven't had the availability to maintain support for ParaView here -- I suspect the plugin infrastructure in ParaView has changed significantly and these will not work. For the past year or so, I've been telling people that I can no longer support ParaView here as its has maybe one or two people who'd actually use it. I am still supporting these tools to be used with PyVista though. PyVista is akin to ParaView, just all in Python.

https://docs.pyvista.org/version/stable/

**Comment by banesullivan** [comment]
All of the "Quick Examples" show how to use PVGeo with ParaView: https://pvgeo.org/examples/index.html

**Comment by Geoscientist1** [comment]
Thank you very much for the quick reply!

**Comment by banesullivan** [comment]
I have dropped support for ParaView, please use PyVista instead: docs.pyvista.org
