### ISSUE TITLE
No module named 'pyvista.core.utilities'

### ISSUE THREAD

**Issue by paitor** [OpenGeoVis/PVGeo#114]
Hi 

Installing PVGeo using pip and running python 3.6.9 installs pyvista 0.33.3 in which pyvista.core.utilities does not exist. Reading up on pyvista I note the pyvista.utilities were split into pyvista.core.utilities and pyvista.plotting.utilities in PR  #4486  the not entirely clear to me which version of pyvista this was merged into. Perhaps worth looking into to set the dependencies straight.

**Comment by banesullivan** [comment]
Unfortunately, PyVista no longer supports Python 3.6. You'll need to install an older version of PVGeo that is compatible with the version of PyVista you have on Python 3.6. Likely just `pvgeo<3`

**Comment by banesullivan** [comment]
Closing this issue as `PVGeo==3.0.1` is released and `PVGeo==3.0.0` has been yanked. This should help mitigate these version incompatibilities though no guarantees as on Python 3.8+ is supported at this time
