### ISSUE TITLE
problem in load new plugins

### ISSUE THREAD

**Issue by wangyf** [OpenGeoVis/PVGeo#22]
Hi:

I encounter a problem when I load new PVGeo plugins. As you noted, I load .py files in my PVplugins folders but output screen of paraview reminds me:

![screen shot 2018-08-30 at 9 18 20 pm](https://user-images.githubusercontent.com/568839/44892552-40637100-ac9a-11e8-992d-48f173a8dc42.png).

Can you help me figure it out? The previous steps seem correct and the procedure of "import PVGeo, pvmacros" seems nothing wrong. My paraview is 5.4.1

**Comment by banesullivan** [comment]
Hi @wangyf, this should be as simple as updating ParaView to the nightly build as PV version 5.4.1 is not compatible with PVGeo’s plugins.

We are currently building PVGeo using **brand new functionality in ParaView** that enables VTK Python algorithms to be decorated with GUI elements and loaded as plugins to ParaView. 

If you followed the install instructions to properly set up your paths for PVGeo then you should be good to go if you install the nightly build to load the plugins. 

Let me know if you run into any other challenges!

**Comment by banesullivan** [comment]
Hi @wangyf, I hope you had a chance to upgrade ParaView and successfully install PVGeo. I'd like to also recommend you join PVGeo on Slack: http://slack.pvgeo.org

**Comment by banesullivan** [comment]
Resolved by using ParaView 5.6 and above
