### ISSUE TITLE
Points to tube does not have apply attribute

### ISSUE THREAD

**Issue by Leguark** [OpenGeoVis/PVGeo#46]
**Describe the bug**
Hi Bane, we are just try to plot some wells in vtk and I was looking to replicate your points to tube example but I think something is not update or it is the vtk version maybe?
**Behavior**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-5570e81fb991> in <module>
      1 # Use the filter: here is vtkPolyData containing the tube
----> 2 tube = PointsToTube(nearestNbr=True).apply(points)
      3 tube.plot(color=True)

AttributeError: 'PointsToTube' object has no attribute 'apply'

Any fast idea?

**Comment by banesullivan** [comment]
Ahhh yes, this is because I'm frantically trying to release version `2.0.0` which updates PVGeo for use with `vista` and changes everything to pep8.

I'm very sorry for the delay on this release. I'm going to push a new pre-release to PyPI so could you please pip install that when it lands or install from the master branch?:

```bash
python -m pip install git+git://github.com/OpenGeoVis/PVGeo@master
```

**Comment by banesullivan** [comment]
`v2.0.0b` should be on PyPI soon - `PVGeo` still has some quirks that need to be fixed before I can push out a full `v2.0.0` release but it shouldn't take too long!

**Comment by Leguark** [comment]
Yes, I imagined so. No worries, it was just in case you were not aware of this specific case. We are trying to couple welly and gempy and I was just playing with the feature. No rush!

**Comment by banesullivan** [comment]
`v2.0.0` is live on PyPI now! Sorry for the delay

Also, do let me know if you have any questions about how PVGeo might fit into `welly` and `GemPy`
