### ISSUE TITLE
Fail to load plugins 

### ISSUE THREAD

**Issue by ZiXuanWan1994** [OpenGeoVis/PVGeo#53]
Dear developer:
I have installed PVGeo module in the virtual environment with pyenv virtualenv and lt's seem everthing is ok. However, when I import the plugin in paraview, the proble came to me as follow:
----------------------------------------------------------------------------------------------------
Generic Warning: In /home/buildslave/dashboards/buildbot/paraview-pvbinsdash-linux-shared-release_superbuild/build/superbuild/paraview/src/ParaViewCore/PythonAlgorithm/vtkPVPythonAlgorithmPlugin.cxx, line 185
Failed to load Python plugin:
Failed to call `paraview.detail.pythonalgorithm.load_plugin`.

Traceback (most recent call last):
  File "/home/wzx/ParaView-5.6.0-MPI-Linux-64bit/lib/python2.7/site-packages/paraview/detail/pythonalgorithm.py", line 513, in load_plugin
    module = imp.load_source(modulename, filepath)
  File "/home/wzx/.pyenv/versions/anaconda2-4.4.0/envs/pvgeoenv/lib/python2.7/site-packages/PVPlugins/PVGeo_All.py", line 11, in <module>
    from PVGeo_Filters import *
  File "/home/wzx/.pyenv/versions/anaconda2-4.4.0/envs/pvgeoenv/lib/python2.7/site-packages/PVPlugins/PVGeo_Filters.py", line 9, in <module>
    import PVGeo
ImportError: No module named PVGeo
ERROR: In /home/buildslave/dashboards/buildbot/paraview-pvbinsdash-linux-shared-release_superbuild/build/superbuild/paraview/src/ParaViewCore/ClientServerCore/Core/vtkPVPluginLoader.cxx, line 403
vtkPVPluginLoader (0x85806d0): /home/wzx/.pyenv/versions/anaconda2-4.4.0/envs/pvgeoenv/lib/python2.7/site-packages/PVPlugins/PVGeo_All.py: 无效的 ELF 头
------------------------------------------------------------------------------------------
It's seem like that Paraview's python environment can't found PVGeo module. How to link the PVGeo to Paraview properly?
Need you help.

**Comment by banesullivan** [comment]
@ZiXuanWan1994 - Do you need help still or are you up and running?

**Comment by ZiXuanWan1994** [comment]
Thank you for concern! I have successfully installed and ran.

**Comment by czdong2001** [comment]
@ZiXuanWan1994  I encountered the same problem, can you tell me how to solve it?

**Comment by czdong2001** [comment]
@banesullivan would you like to help me please?

**Comment by banesullivan** [comment]
@czdong2001, your `PYTHONPATH` environment variable likely needs to point to the `site-packages` directory that PVGeo is installed to

FYI: someone recently posted an excellent installation guide here: https://www.linkedin.com/pulse/paraview-pvgeo-plugins-howto-alexey-pechnikov/
