### ISSUE TITLE
Visualization when using PVGeo in an external python IDE

### ISSUE THREAD

**Issue by L4student** [OpenGeoVis/PVGeo#58]
Hello. I am interested in using this package to do some analysis with multiple 3D mesh, but I am unable to get this to work for me. I started by installing [Using PVGeo in a Python Environment](https://pvgeo.org/overview/getting-started#using-pvgeo-in-a-python-environment), and I am able to import PVGeo in my python environment (IDE outside paraview). Although I have paraview executable (ParaView-5.7.0-Windows-Python3.7-msvc2015-64bit), I am unable to see any plot when I try the [quick examples](https://pvgeo.org/examples/index.html#quick-examples), although running the example itself does not throw any error indicating that the installation is OK. 

I also tried using [PVGeo in Paraview](https://pvgeo.org/overview/getting-started#using-pvgeo-in-paraview), but I could not get step-6 ([here](https://pvgeo.org/overview/getting-started#windows-users)) and [loading the plugins](https://pvgeo.org/overview/getting-started#loading-the-plugins) to work even after multiple attempts, including following everything recommended in [this issue](https://github.com/OpenGeoVis/PVGeo/issues/53). I spent several hours to make sure I am honoring the versions/compatibility issue, but I wasn't able to get this to work.

At this point I am able to get the PVGeo to work with Python (outside the Paraview), but I am not able to see the plots, perhaps because they are meant to be viewed using Paraview only? Could you please help me guide how I can see the plots if I am interested in using PVGeo in an external Python (3.7) IDE (Spyder)?

**Comment by banesullivan** [comment]
Hi @L4student, when not using PVGeo within ParaView (now the recommended use case), it is meant to be used with [PyVista](https://docs.pyvista.org). When you install PVGeo (`pip install PVGeo`), PyVista is installed with it! So no need for ParaView at all.

In brief, PVGeo is a set of file readers and filters that make/process VTK/PyVista mesh objects into other mesh objects. PVGeo does not do any displaying - that's left for either ParaView or PVGeo. So in essence, your question is really on how to get PyVista working in your specific IDE.

When you run an example from the Quick Examples, like [this one](https://pvgeo.org/examples/gslib/read-sgems-grid.html#sphx-glr-examples-gslib-read-sgems-grid-py), you should see PyVista plotting windows appear. They may be somewhere in the background... or perhaps sinnce your IDE spider, it might be running the script in an IPython environment, in which case, PyVista may be fooled by that environment and trying to output a display within the HTML cell outputs like in a jupyter notebook. To resolve that, you would need to add the `notebook=False` argument whenever a PyVista `Plotter` is instantiated.

 Perhaps try a simple example with just PyVista like:

```py
import pyvista as pv

p = pv.Plotter(notebook=False) # make sure to not use IPython notebook embedding
p.add_mesh(pv.Sphere(), show_edges=True)
p.show()
```

If that doesn't work, please share a system report by:

```py
import pyvista as pv
print(pv.Report())
```

**Comment by L4student** [comment]
Thank you, @banesullivan ! It looks like the simple example with just PyVista works for me as it shows a beautiful plot of a spherical mesh.  I tried adding the following lines to get it to work for the 'Read SGeMS Grid' [example](https://pvgeo.org/examples/gslib/read-sgems-grid.html#sphx-glr-examples-gslib-read-sgems-grid-py) you suggested, which uses the `plot` option of the PVGeo `grid` object, but it didn't work.

```
p = pv.Plotter(notebook=False) # in the beginning of the code

p.show() # at the end
```

Does the PVGeo has any attribute like `Plotter(notebook=False)` that can be invoked in the code to show the plots?

**Comment by L4student** [comment]
@banesullivan : I tried using the `notebook=False` attribute inside the `plot()`  function of PVGeo, and it seems to work. However, after the first plot shows up, the Python/IDE just hang up and the currently running code (assuming if it's still running) cannot be canceled through `Ctrl + C`. I have to restart the Python/IDE once it hangs up. I tested this couple of times and it hangs up every time on the first figure. The only way to avoid this behavior is to run the specific lines of the code, close the figure (for the console to show the cursor), and then run next lines of code. I have printed the output of the `pv.Report()` in case that is of any help.

```
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

            0.23.0 : pyvista
             8.1.2 : vtk
            1.17.4 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.5.0 : scooby
             3.1.1 : matplotlib
             5.9.2 : PyQt5
            7.11.1 : IPython

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications
```

I am also get the following error if I import `import pyvista as pv` and then call `pv.examples.downloads._download_file()`, but I am able to run this line (`pv.examples.downloads._download_file()`) without error if I do `from pyvista import examples` instead.


```
  File "<ipython-input-1-4659765c4464>", line 9, in <module>
    filename, _ = pv.examples.downloads._download_file('A_WLreferenceCAT.sgems')

AttributeError: module 'pyvista' has no attribute 'examples'
```

**Comment by banesullivan** [comment]
> I tried adding the following lines to get it to work for the 'Read SGeMS Grid' example you suggested, which uses the plot option of the PVGeo grid object, but it didn't work.

In that `plot` call, pass `notebook=False`. That grid object is a PyVista mesh object - PVGeo is simply an extension package to PyVista. You could also not call that `.plot` method and pass that grid object to the `.add_mesh()` just like the sphere in my example above.

> However, after the first plot shows up, the Python/IDE just hang up and the currently running code (assuming if it's still running) cannot be canceled through Ctrl + C. I have to restart the Python/IDE once it hangs up. I tested this couple of times and it hangs up every time on the first figure. The only way to avoid this behavior is to run the specific lines of the code, close the figure (for the console to show the cursor), and then run next lines of code.

So this is expected behavior. When you `show` the basic `Plotter` object, it takes over the thread so that the script will not continue until the `Plotter` is closed (either by the exit button or pressing `q`). If you want an interactive plotting window, then you might want to checkout [PyVista's `BackgroundPlotter`](https://docs.pyvista.org/plotting/qt_plotting.html?highlight=backgroundplotter#background-plotting).

> I am also get the following error if I import import pyvista as pv and then call pv.examples.downloads._download_file(), but I am able to run this line (pv.examples.downloads._download_file()) without error if I do from pyvista import examples instead.

Again this is expected. `examples` is a seperate module, so it must be imported on it's own. i.e.:

```py
from pyvista import examples

examples.downloads._download_file(...)
```

----

I'd highly recommend you head over to PyVista's docs as you are really using PyVista with a few add ons from PVGeo (PVGeo is not a standalone package, it is an extension package to PyVista). Maybe check out the Getting Started chapter starting with Basic API Usage](https://docs.pyvista.org/getting-started/simple.html) and work your way to PyVista's [Quick Examples](https://docs.pyvista.org/examples/index.html)

**Comment by L4student** [comment]
Thank you for the clarification and recommending the appropriate docs. I will go through the suggested docs.

**Comment by banesullivan** [comment]
Hope this helps! Let me know if there is anything else and feel free to close this issue once you are up and running
