### ISSUE TITLE
problem with VTK on Windows

### ISSUE THREAD

**Issue by bistek** [OpenGeoVis/PVGeo#59]
Hello, I have Anaconda on Windows 10 and I have problems installing PVGeo.

Anaconda is up-to-date: Anaconda 3 2019.10 with Python 3.7.4.

I have installed VTK with: `conda install -c conda-forge vtk`

All other requirements seem OK and I have installed pyvista without any problem (with conda).

When I try to install PVGeo I get an error saying that the VTK package version cannot be resolved, and so PVGeo cannot be installed:

```
Installing collected packages: vtk, pvgeo
  Found existing installation: vtk -PKG-VERSION
ERROR: Cannot uninstall 'vtk'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by banesullivan** [comment]
Make sure you are using the `pip` managed by anaconda when installing PVGeo. It seems likely that you're using the system Python's version of `pip`.

are you running the install from the anaconda-prompt? If not, maybe try that.

Or do:

```bash
python -m pip install PVGeo
```

**Comment by bistek** [comment]
Sorry, I still have the same problem:

```
Installing collected packages: vtk, PVGeo
  Found existing installation: vtk -PKG-VERSION
ERROR: Cannot uninstall 'vtk'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by bistek** [comment]
Hi, I found I had the conda version of VTK, that does not show properly the release version when interrogated by pip:

```
(base) C:\Users\bistek>pip show vtk
Name: vtk
Version: -PKG-VERSION
Summary: VTK is an open-source toolkit for 3D computer graphics, image processing, and visualization
Home-page: None
Author: None
Author-email: None
License: None
Location: c:\users\bistek\anaconda3\lib\site-packages
Requires:
Required-by: pyvista
```

So I removed it, and reinstalled with pip (with python -m option):

```
conda uninstall vtk
python -m pip install vtk
```

And finally I was able to install PVGeo:

`python -m pip install PVGeo`

I think this issue might be closed, but maybe you can update the installation instructions. For some reason the conda vtk was not a problem for PyVista and this was misleading for me.

Thanks a lot!

**Comment by banesullivan** [comment]
huh, that's weird. I think this is a rare/odd windows anaconda issue with your paths. 

Glad you figured it out!

we should really set up a conda-forge recipe for PVGeo to avoid `pip` altogether. Especially with the work being done to bring https://github.com/conda-forge/paraview-feedstock to all OS

**Comment by leomiquelutti** [comment]
I just faced the same issue with both `omfvista` and `pvgeo`.

I installed `pyvista` through `conda install -c conda-forge pyvista`, but could not install `omfvista` or `pvgeo` through `pip`. 

The solution 
> ```
> conda uninstall vtk
> python -m pip install vtk
> ```
offered by @bistek worked for me.

**Comment by banesullivan** [comment]
Might be time I get PVGeo and omfvista on conda-forge then
