### ISSUE TITLE
Trouble viewing the demos?

### ISSUE THREAD

**Issue by banesullivan** [OpenGeoVis/PVGeo#6]
Is anyone having any trouble viewing the demos like the one embedded on the home page of http://pvgp.io or trouble viewing full page renderings like:

- http://volcano.gpvis.org
- http://tunnels.gpvis.org
- http://gpvis.org/?fileURL=https://dl.dropbox.com/s/qybpnsn11lghnq9/OcTree.vtkjs?dl=0

Our current best guess as to why people might have trouble is due to having **Javascript** disabled. The demos require Javascript, so first please enable Javascript in your browser's preferences.

**If you are having troubles, please post the following details:**

1. Describe what you see on the trouble pages: *[e.g. a blank page; a gray window; server not found]*
2. Your operating system and browser: *[e.g. MacOS and Safari; iOS and mobile Chrome]*
3. Your general location in the world: *[e.g. Colorado, USA; London, UK]*
4. Specific links if some work and others do not

**Comment by craigmillernz** [comment]
Tried it again on another PC and works fine. Windows 10. from NZ
