### ISSUE TITLE
PVGeo + python, ErrorObserver not muting vtk

### ISSUE THREAD

**Issue by FlorianFSA** [OpenGeoVis/PVGeo#63]
**Bug description**
_I'm running in Python outside of Paraview._

When a vtk error occurs, a python exception is successfully raised by the ErrorObserver but the original vtk raw error is still printed.

**To Reproduce**
I used a slighty modified version of the code snippet provided in PVGeo._helpers.errors
```
#!/usr/bin/env python3
import PVGeo

def main():
	f = PVGeo.AlgorithmBase()
	f.Update()
	if f.error_occurred():
		print("PVGeo Error message ==>", f.get_error_message())


if __name__ == "__main__":
    main()
```

The output:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/54753760/87366120-3722db00-c578-11ea-8fd7-2ee4c011e5ed.png">

1. **First error is the raw vtk error**
2. Next is the error printed by the helper
3. Third is the error manually printed by the code snippet 

The part that is bothering me is the raw vtk error. From what I understand adding an error observer was supposed to catch the vtk error and make it "transparent".
Also the vtk raw error is not outputting in stdout.

Consequently if the error management is working (exceptions still fired) the terminal output is messy. 

**Concerned installation**
 - MacOS
 - Python 3.7.4
 - Packages :
```
appdirs==1.4.4
espatools==0.1.0
imageio==2.9.0
importlib-metadata==1.7.0
meshio==4.0.16
numpy==1.19.0
pandas==1.0.5
Pillow==7.2.0
properties==0.6.1
PVGeo==2.1.0
python-dateutil==2.8.1
pytz==2020.1
pyvista==0.25.3
scipy==1.5.1
scooby==0.5.6
six==1.15.0
vectormath==0.2.2
vtk==9.0.1
xmltodict==0.12.0
zipp==3.1.0
```
(only PVGeo was installed through pip)

**Comment by banesullivan** [comment]
> The part that is bothering me is the raw vtk error. From what I understand adding an error observer was supposed to catch the vtk error and make it "transparent".

This is correct. This appears to be an issue with VTK 9

**Comment by FlorianFSA** [comment]
Thanks for the confirmation of the expected behavior ! 

For information, if this issue is bothering someone else, I tried to fiddle around within the source of PVGeo searching for a magical vtk option with no luck. 
I tried a lot of things with vtkOutputWindow but non of them worked.

I only managed to completely shut down all form of error management by calling the '''[vtkObject].GlobalWarningDisplayOff()''' function (for a specific object or globally). 

**But** this function prevent the triggering of the ErrorObserver and thus break the exception handling, which actually makes sense. It can be used but must be used knowingly.

Since the exception handling is working perfectly well as is, I chose to ignore these unwanted outputs and wait for a fix from vtk. 

From what I understand this is a known issue ?

**Comment by banesullivan** [comment]
> From what I understand this is a known issue ?

Known to you and me now! I don't think this is documented elsewhere. This is probably worth reporting upstream in VTK

**Comment by FlorianFSA** [comment]
I added an issue to VTK > [https://gitlab.kitware.com/vtk/vtk/-/issues/17958](https://gitlab.kitware.com/vtk/vtk/-/issues/17958)

**Comment by banesullivan** [comment]
Thanks for posting there, @FlorianFSA. I am going to close this issue and follow that one
