### ISSUE TITLE
PVGeo Golden Software Surfer grid writer 

### ISSUE THREAD

**Issue by trhoye** [OpenGeoVis/PVGeo#66]
**Thank you for the "PVGeo surfer binary grid reader"  ;-)
What about a binary grid writer? .**

**Here is my ASCII Surfer grid writer (very simple)**

````
def write_surfer_ascii_grid(filename,grid,data,mybounds,ncol):
    nx,ny,nz = grid.dimensions
    xmin,xmax,ymin,ymax,zmin,zmax = mybounds # - - - see commented below
    with open(filename,'w') as f:
        f.write('DSAA'+'\n')
        f.write(str(nx)+' '+str(ny)+'\n')
        f.write(str(xmin)+' '+str(xmax)+'\n')
        f.write(str(ymin)+' '+str(ymax)+'\n')
        f.write(str(zmin)+' '+str(zmax)+'\n')<
    data=data.reshape(ny,nx,1)
    data=np.swapaxes(data,0,1)
    with open(fname,'a') as f:
        for j in range(ny):
            np.savetxt(f,data[:nx,j])
            f.write(' \n')

**Comment by trhoye** [comment]
A problem detected
The **xmax, ymax** bounds was changed after:  **surface.warp_by_scalar(scale_factor=1)**
=> The map expported to surfer was slightly shrinked.
I.e. You need to pick the correct **xmax and ymax** bounds from **surface**, 
and correct **zmin and zmax** from  **map = surface.warp_by_scalar(scale_factor=1)**

quick fix :
```
# importing a map from surfer
surface = SurferGridReader().apply(filename)
mymap = surface.warp_by_scalar(scale_factor=1)
#
mybounds=surface.bounds
mybounds[4] = mymap.bounds[4]
mybounds[5] = mymap.bounds[5]

add  (mybounds) to the    write_surfer_ascii_grid function
      xmin,xmax,ymin,ymax,zmin,zmax = mybounds

**Comment by banesullivan** [comment]
If there are any NaN scalar values then the nodes of those will be removed by the `warp_by_scalar` PyVista filter. Hence a change in XY extent could occur if there is NaN/null-data on the edges of the mesh (this is very common)

**Comment by banesullivan** [comment]
However, thanks for sharing your Surfer ASCII grid writer! I'll see if I can find time to merge that into PVGeo as a new exporter
