### ISSUE TITLE
The map receives from EsriGridReader is upside down ?

### ISSUE THREAD

**Issue by leminhson** [OpenGeoVis/PVGeo#67]
**Describe the bug**
A mesh imported from ArcInfo ASCII grid file using EsriGridReader function of fileio.py is displayed upside down.

**Behavior**
The latitude of an Esri grid map received from EsriGridReader function is in the wrong order.

**To Reproduce**
The ArcInfo ASCII grid files could be downloaded from : _https://ags.aer.ca/publications/MOD_2018_02.html_
(Alberta Geological Survey (2019): 3D provincial geological framework model of Alberta, Version 2 - metadata and methodology)

For example, a data file of bedrock topography top surface is a file: _cmh_02b_Pg_Pa_PH_top.asc_

**Data format:**
According to the web page _https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/esri-ascii-raster-format.htm_:

> The data component of the Esri ASCII raster follows the header information.
> Cell values should be delimited by spaces.
> No carriage returns are necessary at the end of each row in the raster. The number of columns in the header determines when a new row begins.
> **Row 1 of the data is at the top of the raster, row 2 is just under row 1, and so on**.

That means: the first row in data file has the highest latitude (corresponding to the top row on a map); last row in data file has lowest latitude (corresponding to the bottom row on a map)

Therefore, EsriGridReader function should read .asc data file from the bottom to the top, not from the top to bottom.

**Screenshots**
Bedrock topology top:
![bedrock](https://user-images.githubusercontent.com/14102005/91638362-4cc16680-ea39-11ea-98ad-d2aff203a7e4.png)

A mesh is produced by EsriGridReader function (wrong latitude):
![upside_down](https://user-images.githubusercontent.com/14102005/91638388-84301300-ea39-11ea-9fed-34ea1c4a751d.png)

A mesh should be like this:
![correct_direction](https://user-images.githubusercontent.com/14102005/91638396-927e2f00-ea39-11ea-9697-9b81b27a10e1.png)

**Desktop:**
 - OS: Windows 7 64bit
 - Python Version: 3.8
 - NumPy Version: 1.19.1
 - PVGeo Version: 2.1.0

**Comment by banesullivan** [comment]
Wow, thank you for the detailed description of this bug and the details on the proper way to read the mesh! I will get to making a patch for this ASAP
