### ISSUE TITLE
EsriGridReader returns wrong data if a grid file has NODATA_VALUE

### ISSUE THREAD

**Issue by leminhson** [OpenGeoVis/PVGeo#68]
**Describe the bug**
The structured grid received from EsriGridReader is correct if all pixels have normal values. But if there are some NODATA_VALUE in a data grid file, EsriGridReader will returns wrong a structured grid.

**To Reproduce**
Here is a simple code to reproduce the error:
![simple code](https://user-images.githubusercontent.com/14102005/92936143-f231fc80-f473-11ea-8091-02d6bdb95388.png)

**Data file:**
Download data files and soure code: [Error_NODATA.zip](https://github.com/OpenGeoVis/PVGeo/files/5209692/Error_NODATA.zip)
vd0.asc ; data for the top layer
vd1.asc : data for the bottom layer without NODATA_VALUE
vd2.asc : data for the bottom layer with three pixel of NODATA_VALUE

**Screenshots**
If a data file does not have NODATA_VALUE, the bottom layer is correct.
**Correct bottom layer:**
![correct layers](https://user-images.githubusercontent.com/14102005/92938968-64f0a700-f477-11ea-94c9-d7a2e49e1b6a.png)

But if there are some NODATA_VALUE in a data file, the first point in a structure grid of the bottom layer becomes _**'nan'**_ although this pixel has a value actually.
**Error bottom layer:**
![error layers](https://user-images.githubusercontent.com/14102005/92938908-5609f480-f477-11ea-9aa2-156b66e29817.png)

**Where is the bug ???**
After checking the source of EsriGridReader, I found that the command **_data[nans] = np.nan_** at line 496 of the function  **_get_raw_data_** assigns **'nan'** for points[0] automatically.
Actually, we have only three **_'nan'_** values at points[12], points[17] and points[22]. But why points[0] also changes to **_'nan'_** ?
![Error_nan](https://user-images.githubusercontent.com/14102005/92939997-b77e9300-f478-11ea-967a-7b67be1ba0f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 64bit
 - PVGeo: 2.10
 - NumPy Version: 1.19.1

**Comment by banesullivan** [comment]
Thanks for providing a detailed example, @leminhson! I'll try to tackle this as soon as I can

**Comment by banesullivan** [comment]
This turned out to be a rather simple fix. The argwhere was evaluating on a 2D array that had been flattened to one column so it included that column's zero index. Simply flattening the array fixed it.

**Comment by leminhson** [comment]
@banesullivan : Thank you for your prompt fixing

**Comment by banesullivan** [comment]
It may be a little while before I push out a release to PyPI (have to fix a bit of broken CI), but the changes (see #69) will be on master soon
