### ISSUE TITLE
Voxelize model with known block size

### ISSUE THREAD

**Issue by javoha** [OpenGeoVis/PVGeo#71]
Hello everyone,

lately I have been trying to create a voxelized ("block") model. The data I want to visualize is based on x,y,z data that was grided before, but does not cover a whole cuboid space. When the orginial grid that the data is retrieved from is regularly spaced, I am able to get a nice voxelized model using `PVGeo.filters.VoxelizePoints()` . 
However, in my real application case the orginal grid is not cubic, but instead I have different length in different directions. I do know the resolution of the original grid (thus also the voxel size I am aiming for).  When using `PVGeo.filters.VoxelizePoints()`  I get a result that doesnt cover the whole space - there are gaps between voxels and maybe also some overlapping.

Maybe I am missing a simple solution (maybe even jsut in pyvista) for this as I know the original resolution. Some help or ideas would be highly appreciated. 

Thanks a lot for any help and support and of course for your time!

**Comment by banesullivan** [comment]
It's tough to tell what's going on without the data... Can you share a file and sceenshots?

**Comment by banesullivan** [comment]
FYI, the pyvista support forum gets more visibility than this repo: https://github.com/pyvista/pyvista-support

**Comment by javoha** [comment]
Hi @banesullivan,

thanks for taking a look. Should I move the issue to Pyvista or just keep it here for now?

Maybe for some context - I am on working in gempy. My aim is to populate single units of a gempy model with property values (e.g. density) and display the result as a voxel model. Here a simple test model of a foreset kind of setting that I am using (2.5D):

![image](https://user-images.githubusercontent.com/38279459/110910683-f9966d80-8311-11eb-85c7-408b82606801.png)

I extract the grid data for the red unit (domain of interest) and populate it with density values using SGS or Kriging. If my orginal gempy model had a evenly spaced resolution (e.g extent of model [1000,1000,1000] and resolution [100,100,100] in this example, I get a nice result using the `PVGeo.filters.VoxelizePoints()`:

![image](https://user-images.githubusercontent.com/38279459/110911309-d28c6b80-8312-11eb-8338-248d658426b5.png)

If my grid grid is not evenly spaced though (here extend still [1000,1000,1000] but res [100,50,100]), the resulting voxel volume does not fill the whole space, as seen here:

![image](https://user-images.githubusercontent.com/38279459/110911190-a83aae00-8312-11eb-9e1a-74b839c256ae.png)

Probably I am missing a simple pyvista solution to this, just wasnt able to find a nice one yet.

Again thanks a lot for checking it out, I am grateful for any help or hints!

**Comment by banesullivan** [comment]
Keep the issue here for now. There is likely a simpler solution with PyVista. Can you show me/send me whatever input you're passing to `PVGeo.filters.VoxelizePoints`?

e.g.

```py
points.save('points.vtk')
```

**Comment by banesullivan** [comment]
PVGeo's `VoxelizePoints` does not currently handle non-uniform grid cells

**Comment by javoha** [comment]
The unstrucutrued grid for pyvista is created based on x,y, z and property value (called `field`) using the workflow from GSTools. Here a screenshot of the resulting unstructured grid for the second example shown before:

![image](https://user-images.githubusercontent.com/38279459/111128280-01098100-8575-11eb-8434-9567ea77c137.png)

This is also what I feed the voxelizer:

`grid = PVGeo.filters.VoxelizePoints().apply(pc)` 

I also attached the points file as you suggested:

[points](https://gigamove.rz.rwth-aachen.de/d/id/zpKgQojRBKLKMb)

Thanks again for helping.

**Comment by banesullivan** [comment]
> If my grid grid is not evenly spaced though (here extend still [1000,1000,1000] but res [100,50,100]), the resulting voxel volume does not fill the whole space, as seen here:

Ah, actually I just realized you know the grid spacing ahead of time. `VoxelizePoints` cannot figure out the non-uniform spacing on its own but it can handle non-uniform spacing if it is informed via the `dx`, `dy`, `dz`, and `estimate` arguments.

Try:

```py
grid = PVGeo.filters.VoxelizePoints(dx=10, dy=20, dz=10, estimate=False).apply(pc)
```

FYI, this is not documented. I only know because I wrote the algorithm.

Also, I noticed that the res of the points is different than what you commented above.

```py
>>> spacing = lambda arr: np.unique(np.diff(np.unique(arr)))
>>> spacing(pc.points[:,0]), spacing(pc.points[:,1]), spacing(pc.points[:,2])
(pyvista_ndarray([10.]), pyvista_ndarray([20.]), pyvista_ndarray([10.]))
```
----

![Screen Shot 2021-03-16 at 12 38 34 PM](https://user-images.githubusercontent.com/22067021/111362760-cf67e700-8654-11eb-9e96-ef0f499d92b7.png)

**Comment by javoha** [comment]
Perfect, works like a charm. Thanks for your hepl. I suppose this means there is also not a much easier solution just using pyvista?

**Comment by banesullivan** [comment]
I thought there might be by making a `StucturedGrid` of these data but they are indeed unstructured, so this is the best I can think of for now

**Comment by RichardScottOZ** [comment]
Thanks!

I have a similar sort of problem to do with density - where I want to make a density model for which I know the resolution I want - e.g. 30000 * 25000 * 75 - and have a bunch of surfaces of rock units to use (and make) - voxelise?  Not sure of the best/most efficient way to do it.

Basically over the same area - e.g. state of SA - but the surfaces data will be in whatever coordinate system - and coarser resolution vertically,  Blocks will be cubes though! e.g. 50x50x50.

I merged the surfaces that I was working on just to see what it would look like - whether it is better to do them all separately?

![image](https://user-images.githubusercontent.com/72196131/114529163-d7816980-9c88-11eb-811c-cddff54064a6.png)

![image](https://user-images.githubusercontent.com/72196131/114529218-e36d2b80-9c88-11eb-96ad-fcf04ce350a6.png)

**Comment by RichardScottOZ** [comment]
Eventually into a floating point Zarr datastore as such

![image](https://user-images.githubusercontent.com/72196131/114531805-62636380-9c8b-11eb-8eee-7c4094ba9364.png)

**Comment by RichardScottOZ** [comment]
There'll be more surfaces to go into the above, just haven't made it yet. 76 Z being like 1300m above ground and 2500 under in this case.

**Comment by RichardScottOZ** [comment]
Making a gempy version at whatever resolution to look at will be good, too @javoha

**Comment by RichardScottOZ** [comment]
One of the various 100+ surfaces looks like this 
![image](https://user-images.githubusercontent.com/72196131/114532426-fcc3a700-9c8b-11eb-9ea7-b0ad4aa84909.png)

**Comment by RichardScottOZ** [comment]
I 'high density number' voxelised that to have a look  
![image](https://user-images.githubusercontent.com/72196131/114532553-18c74880-9c8c-11eb-9014-dce0f6ced1b8.png)

**Comment by banesullivan** [comment]
@RichardScottOZ, I'm not following what you're hoping to do... I'd suggest opening a new support topic in the PyVista forum

**Comment by banesullivan** [comment]
Closing this as the original issue using `PVGeo.filters.VoxelizePoints` is resolved

**Comment by RichardScottOZ** [comment]
Ok, will do, thanks!

**Comment by RichardScottOZ** [comment]
Done in https://github.com/pyvista/pyvista-support/issues/404
