### ISSUE TITLE
PVGeo reader Paraview

### ISSUE THREAD

**Issue by FrankForster** [OpenGeoVis/PVGeo#72]
Hello,

I installed Paraview + PVGeo and dependencies following these instructions : https://pvgeo.org/overview/getting-started.html

I tried with Python 2.7 & 3.7 & 3.9 but I always end up in Paraview showing me VTK errors.

Given that the instructions suggest Python 2.7, is the PVGeo reader in Paraview not compatible at this time or I am wrongfully installing it ? 

Thanks you in advance,

Frank

**Comment by banesullivan** [comment]
Support within ParaView has fallen to the wayside lately. I recommend using PVGeo with PyVista at this time.

I am working to bring back full support with the latest ParaView (Python 3.x)... stay tuned

**Comment by frank11000** [comment]
Thank you for your short answer, I'm going with PyVista until further developments. Best regards

**Comment by banesullivan** [comment]
Working on this... currently blocked by https://github.com/pyvista/pyvista/issues/3224

**Comment by banesullivan** [comment]
I have dropped support for ParaView, please use PyVista instead: docs.pyvista.org
