### ISSUE TITLE
import pvmacro problem

### ISSUE THREAD

**Issue by craigmillernz** [OpenGeoVis/PVGeo#9]
Hi
I've update to the new PVGeo (0.7.3) from the old PVGP

i've updated the plugins path and python path.

When i try to import pvmacros in the paraview python console I get the following error.

I'm running windows10 with anaconda3

>>> import PVGeo
>>> 
>>> import pvmacros
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\Dropbox\GIT\PVGeo\pvmacros\__init__.py", line 6, in <module>
    from . import vis
  File "D:\Dropbox\GIT\PVGeo\pvmacros\vis\__init__.py", line 4, in <module>
    from .slices import *
  File "D:\Dropbox\GIT\PVGeo\pvmacros\vis\slices.py", line 6, in <module>
    from scipy.spatial import cKDTree
ImportError: No module named scipy.spatial

**Comment by banesullivan** [comment]
Hi @craigmillernz I just pushed a change to the master branch that puts the scipy.spatial import internally to the method that needs it: [`manySlicesAlongPoints()`](http://pvgeo.org/pvmacros/vis/many-slices-along-points/)

The rest of the `pvmacros` module can be used without scipy, however if you’d like to use [`manySlicesAlongPoints()`](http://pvgeo.org/pvmacros/vis/many-slices-along-points/) then a quick fix is to update the scipy module in ParaView’s application contents or better yet to delete it if your paths are set up for a specific Python environment. When using python inside ParaView, it first searches the application contents to import modules and unfortunately I think the scipy version shipped with ParaView is quite old. 
 
Try deleting/replacing the scipy module in ParaView’s application folder. This is a dirty quick fix that will work. I will work on developing a tutorial on how to activate a virtual environment to use directly in ParaView much like [this blog post](https://blog.kitware.com/using-pvpython-and-virtualenv/) when I get back in town next week. 

Hope this helps!

**Comment by banesullivan** [comment]
My previous post has been heavily edited.

**Q:** I am also curious what version of SciPy is being imported?
```py
import scipy
print(scipy.__version__)
```

**Comment by craigmillernz** [comment]
Hi Bane

Thanks, I saw your reply and pulled the new update. The pvmacro module now loads.
However when I tried to import scipy it doesn’t have it.  I have paraview v5.5.0 64bit

import scipy
Traceback (most recent call last):
File "<console>", line 1, in <module>
ImportError: No module named scipy

I did a bit of googling and it seems scipy doesn't ship with the windows version of paraview5.5.0.

I don't think it's an issue for what i need, but might be an issue for others.

C

**Comment by banesullivan** [comment]
Thanks for the investigating, @craigmillernz. I will make a note to add this to the [Getting Started Page](http://pvgeo.org/overview/getting-started/) and I will try to get some info up on how to pair a virtual environment with ParaView's Python to control what packages get imported.

**Comment by banesullivan** [comment]
New installation instructions using a virtual environment should fix this issue: [Details](http://pvgeo.org/overview/getting-started/#install-paraview)
